config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :users do
    get 'download'

  end
  post 'users/delete_selected_user'

  resources :todo_lists do
    collection { post :import }
    resources  :todo_items
  end

  root 'todo_lists#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

 validates :content ,presence: true,uniqueness:true,length: { maximum: 500 }

end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  def new
    @todo_items =TodoItem.new
  end

  def create
    @todo_list = TodoList.find(params[:todo_list_id])
    @todo_items = @todo_list.todo_items.create(todo_list_params)
    redirect_to @todo_list
  end

  def destroy
    puts params[:id]
   @todo_items=@todo_list.todo_items.find(params[:id])
    if @todo_items.destroy
       flash[:sucess] = "Todo Item was Deleted"
    else
      flash[:error] = "Not Able To Delete"
    end

  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

   def todo_list_params
     params[:todo_item].permit(:content)
   end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<%= form_for ([@todo_list , @todo_list.todo_items.build]) do |f| %>
    <%= f.label :content%>
    <%= f.text_field :content %>

    <%= f.submit%>
<%end%>

app/views/todo_items/_todo_item.html.erb
<table class="table table-bordered ">
<% i=1 %>
  <tr>
    <th>Content</th>
    <th>Action</th>
   </tr>
<% @todo_items.each do |item| %>
 <tr>
 <td><%= item.content %></td>

   <td><%= link_to 'Delete' , todo_list_todo_item_path(@todo_list,todo_item.id),method: :delete,data:{confirm: "Are You Sure?"} %>
 </tr>
<%end%>
</table>