config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :users do
    get 'download'

  end
  post 'users/delete_selected_user'

  resources :todo_lists do
    collection { post :import }
    resources  :todo_items
  end

  root 'todo_lists#index'

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_items

  def name_with_initial
     "#{content}"
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |todo_list|
        csv << todo_list.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    array = Array.new
    CSV.foreach(file.path , col_sep:',') do |row |
         array.push(row[1])
      #TodoList.create! row.to_hash
    end
    i=0
    array.each_with_index do |element,index|
       i=i+1
       puts element[]
    end

  end

 #validates :title ,:presence => true ,uniqueness: true
#validates :description ,:presence => true
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
      @todo_lists = TodoList.all
      respond_to do |format|
        format.html
        format.csv {send_data @todo_lists.to_csv}
        format.xls  #{send_data @todo_list.to_csv(col_sep: "/t" ) }
      end
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    @todo_items=TodoItem.all
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    TodoList.import(params[:file])
    redirect_to root_url ,notice: "TodoList Item Imported"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>
      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

    <div class="field">
      <%= check_box("hobbies", "Codeing", {} ,"yes" , "no") %>
      <%= check_box("hobbies", "Management" , {} ,"yes" , "no")%>
      <%= check_box("hobbies", "Playing" , {}, "yes" , "no")%>

      <%= radio_button("todo","gender" ,"Male")%>
      <%= radio_button("todo","gender" ,"Female")%>

      <%= datetime_field("user","born_on")%>
      <%= color_field("hashName", "color")%>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<script>
    FB.getLoginStatus(function(response) {
        statusChangeCallback(response);
    });
</script>
<div class="content">
<p id="notice"><%= notice %></p>

<h1>Listing Todo Lists</h1>

<table class="table table-bordered">
  <thead>
    <tr>
     <td><span style="color:#7014ff">Generate :</span>
     <%= link_to "CSV", todo_lists_path(format: "csv") ,:style=>"color:blue"%>&nbsp;
     <%= link_to "EXCEL" , todo_lists_path(format: "xls") ,:style=>"color:blue"%></h3></td>
    </tr>
    <tr>
      <th> Sr No </th>
      <th> Title </th>
      <th> Description </th>
      <th colspan="3"> Actions </th>
    </tr>
  </thead>
 <% i =0 %>
  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= i=i+1 %></td>
        <td><%= todo_list.title   %></td>
        <td><%= todo_list.description  %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo list', new_todo_list_path %>

<h2>Import Products</h2>
  <%= form_tag import_todo_lists_path , multipart: true do %>
      <%= file_field_tag :file%>
      <%= submit_tag "Import" %>
 <% end %>
<div
class="fb-like"
data-share="true"
data-width="450"
data-show-faces="true">
</div>

<html>
<head>
  <title>Facebook Login JavaScript Example</title>
  <meta charset="UTF-8">
</head>
<body>
<script>
    // This is called with the results from from FB.getLoginStatus().
    function statusChangeCallback(response) {
        console.log('statusChangeCallback');
        console.log(response);
        // The response object is returned with a status field that lets the
        // app know the current login status of the person.
        // Full docs on the response object can be found in the documentation
        // for FB.getLoginStatus().
        if (response.status === 'connected') {
            // Logged into your app and Facebook.
            testAPI();
        } else if (response.status === 'not_authorized') {
            // The person is logged into Facebook, but not your app.
            document.getElementById('status').innerHTML = 'Please log ' +
            'into this app.';
        } else {
            // The person is not logged into Facebook, so we're not sure if
            // they are logged into this app or not.
            document.getElementById('status').innerHTML = 'Please log ' +
            'into Facebook.';
        }
    }

    // This function is called when someone finishes with the Login
    // Button.  See the onlogin handler attached to it in the sample
    // code below.
    function checkLoginState() {
        FB.getLoginStatus(function(response) {
            statusChangeCallback(response);
        });
    }

    window.fbAsyncInit = function() {
        FB.init({
            appId      : '{your-app-id}',
            cookie     : true,  // enable cookies to allow the server to access
                                // the session
            xfbml      : true,  // parse social plugins on this page
            version    : 'v2.2' // use version 2.2
        });

        // Now that we've initialized the JavaScript SDK, we call
        // FB.getLoginStatus().  This function gets the state of the
        // person visiting this page and can return one of three states to
        // the callback you provide.  They can be:
        //
        // 1. Logged into your app ('connected')
        // 2. Logged into Facebook, but not your app ('not_authorized')
        // 3. Not logged into Facebook and can't tell if they are logged into
        //    your app or not.
        //
        // These three cases are handled in the callback function.

        FB.getLoginStatus(function(response) {
            statusChangeCallback(response);
        });

    };

    // Load the SDK asynchronously
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    // Here we run a very simple test of the Graph API after login is
    // successful.  See statusChangeCallback() for when this call is made.
    function testAPI() {
        console.log('Welcome!  Fetching your information.... ');
        FB.api('/me', function(response) {
            console.log('Successful login for: ' + response.name);
            document.getElementById('status').innerHTML =
                    'Thanks for logging in, ' + response.name + '!';
        });
    }
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->

<fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
</fb:login-button>

<div id="status">
</div>
</div>
</body>
</html>

app/views/todo_lists/index.xls.erb
<?xml version = "1.0" ?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <ss:Styles>
    <ss:Style ss:ID="1">
      <ss:Font ss:Bold="1"/>
      <ss:Font ss:Color="#0044ff"/>
    </ss:Style>
  </ss:Styles>

  <ss:Styles>
    <ss:Style ss:ID="2">
    </ss:Style>
  </ss:Styles>

  <ss:Styles>
    <ss:Style ss:ID="3">
      <Alignment ss:Vertical="Center"/>
    </ss:Style>
  </ss:Styles>
    <Worksheet Name="Sheet1">
         <Table>
              <Row ss:StyleID="2" >
                 <Cell ss:MergeAcross="2" ss:StyleID="3"><Data Type="String">Todo List </Data></Cell>
              </Row>
             <Row ss:StyleID="1" >
               <Cell><Data Type="String">ID</Data></Cell>
               <Cell><Data Type="String">Title</Data></Cell>
               <Cell><Data Type="String">Description</Data></Cell>
             </Row>

         <% @todo_lists.each do |items| %>
               <Column ss:Width="80"/>
               <Column ss:Width="90"/>
               <Column ss:Width="100"/>
           <Row>
               <Cell><Data Type="Integer"><%= items.id %></Data></Cell>
               <Cell><Data Type="String"><%= items.title %></Data></Cell>
               <Cell><Data Type="String"><%= items.description %></Data></Cell>
           </Row>
           <%end%>
         </Table>
    </Worksheet>
</Workbook>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>

<div id="todo_item_list">
  <%= render @todo_list.todo_items %>
  <div class="form">
   <%= render 'todo_items/form'%>
  </div>
</div>
<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>