config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :users do
    get 'download'

  end
  post 'users/delete_selected_user'

  resources :todo_lists do
    collection { post :import }
    resources  :todo_items
  end

  root 'todo_lists#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  #Validations
  has_attached_file :document,
                    :styles => {
                        :thumb => "50x50>",
                        :small => "150x150>"
                    },
                    #:path => '/home/it184/Project/Todo_app/non_public/images.jpeg',
                    #:url => 'users/4/download'
                    :path => ':rails_root/non-public/system/:attachment/:id/:style/:basename.:extension',
                    :url => ':class/:id/:attachment?style=:style/:basename.:extension'


  # def initialize(params = {})
  #   # File is now an instance variable so it can be
  #   # accessed in the validation.
  #
  #   @file = params.delete(:file)
  #   super
  #   if @file
  #     self.filename = @file.original_filename
  #     self.content_type = @file.content_type
  #     self.file_contents = @file.read
  #   end
  # end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "admin" , password:"pass"
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    #@user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        UserMailer.registration_confirmation(@user).deliver
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
     # send_file '/home/it184/Project/Todo_app/non_public/images.jpeg',
     #  :type => 'image/jpeg'
    user = User.find(params[:user_id])
    send_file user.document.path, :type => user.document_content_type
  end

  def delete_selected_user
    puts "````````````````#{params[:check_user][:user_ids]}"
    User.where(:id => params[:check_user][:user_ids]).delete_all
    redirect_to users_url,
    notice: "User's where deleted Successfully !!!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      #params.require(:user).permit(:name, :email, :contact, :file)
      params.require(:user).permit(:name, :email, :contact, :document,:check_user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user,:html => { :multipart => true }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>

   <div class="field">
     <%= f.file_field :document %>
   </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Email Recipients </h1>
<%= form_tag (users_delete_selected_user_path) do %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Select</th>
      <th>Id</th>
      <th>Name</th>
      <th>Email</th>
      <th>Contact</th>
      <th>Attachment</th>
      <th>Photo</th>

      <th colspan="3" align="center">Actions</th>
    </tr>
  </thead>


  <tbody>
    <% @users.each do |user| %>
      <tr>
        <!--<td><%=check_box_tag(:check_user , user.id ,false,:class=>"user_checkbox")%></td>-->
        <td><%= check_box_tag "check_user[user_ids][]",user.id%></td>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.contact %></td>
        <td><%= link_to 'download' ,user_download_path(user.id) %></td>
        <!--<td><%= user.document_file_name %></td>-->
        <td><%= image_tag user.document.url(:thumb) %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    <div class="pull-left">
     <%= link_to 'Create Email', new_user_path ,:class =>"btn btn-primary btn-sm",:style=>"color:white" %>&nbsp;&nbsp;
     <%= submit_tag "Delete",:class =>"btn btn-danger btn-sm" %>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @user.contact %>
</p>

<p>
 <strong>Attachment</strong>
  <%= @user.document_file_name %>
  <%= image_tag @user.document.url(:small) %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>